### ISSUE TITLE
Please update your flutter plugin

### ISSUE THREAD

**Issue by janosroden** [OneSignal/OneSignal-Flutter-SDK#193]
Hi,

The [latest onesignal version for flutter](https://pub.dev/packages/onesignal_flutter/versions) is 2.3.1. Please upload a few (or at least the latest) version.

Apple started to complaining about the use of UIWebView so I need to upgrade to >=2.10.2.
(ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs.)

Thanks in advance,
Janos Roden

**Comment by jkasten2** [comment]
@janosroden [OneSignal-Flutter-SDK 2.3.1](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/2.3.1) already contains the UIWebView fix as it includes OneSignal-iOS-SDK 2.12.2. The issue was fixed in [OneSignal-iOS-SDK](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/2.10.2).

If you have the latest OneSignal-Flutter-SDK in your project I recommend running `pod install` from the iOS folder to ensure flutter pulls down the latest iOS SDK.

**Comment by janosroden** [comment]
Thanks, for some reason I thought the plugin version follows this repo. Sorry for disturb.
