### ISSUE TITLE
iOS device receiving push notifications twice

### ISSUE THREAD

**Issue by callumclift** [OneSignal/OneSignal-Flutter-SDK#195]
Whenever I send a notification to an iOS device the notification is coming through twice. I found something related to this on the onesignal website here: [https://documentation.onesignal.com/docs/duplicated-notifications](url)

I took the advice and restarted my iPhone but i'm still receiving the notification twice, how can i know this wont happen when i publish my app live?

i'm using the latest version of onesignal installed via pubspec: onesignal_flutter: ^2.3.1

**Comment by jkasten2** [comment]
@callumclift How are each of the notifications displaying? As an alert dialog in the app or a banner from the top of the screen? If you swipe down from the top of the screen to bring up the notification center does it show there twice too?

2nd how many receipts are you sending the notification to? If it is more than one check for any duplicate users on your OneSignal app. One way to do this is to view the All Users page on the OneSignal dashboard.

**Comment by callumclift** [comment]
@jkasten2 the notifications are always displaying the same, as a banner from the top of the screen, even when the app is currently open in the foreground. Is there a way this can be changed so that when the app is in the foreground a banner is not seen and I can handle the notification in-app with a dialog or toast message? Firebase messaging allows you to handle foreground messages (but doesn't really work well on iOS ha) can this be done with onesignal?

As for the number of receipts i've checked the response and its only showing as one:

`{id: a3b54f61-b6a3-4788-b0ff-68ffe9305880, recipients: 1, external_id: null}`

This is how all notifcations are received:

[https://imgur.com/MvkHtpF](url)

**Comment by callumclift** [comment]
@jkasten2 Ok so I think it may have been a problem with duplicate users but i'm not entirely sure. When I delete and reinstall my app my iPhone gets a new player-id so in my code i'm sending the message to that new player id only, but is there a chance 2 would be sent if I don't delete the older player-id from the last app install?

**Comment by jkasten2** [comment]
@callumclift If you fully uninstall the app and reinstall it your device will have a new pushToken. The old token stops working right away so a duplicate won't be possible in this case. You will still see the device subscribed for a while however, as it takes Apple's APNs server 1 week or more to report the invalid status for the token. You can confirm this by sending a notification to one user at a time, only the most recent player_id for your device will get the notification.

The duplicate notification issue is due to a different root problem. Can you describe how the notification looked with the details I requested in my last reply?

**Comment by callumclift** [comment]
@jkasten2 I don't know how but i've stopped having this issue now. I reinstalled my app and cleared out the users in the onesignal dashboard and I haven't had any duplicate notifications since
