### ISSUE TITLE
ld: framework not found Flutter

### ISSUE THREAD

**Issue by romatroskin** [OneSignal/OneSignal-Flutter-SDK#210]
Hello! Could not build OneSignalNotificationServiceExtension.
ld: framework not found Flutter

**Comment by jkasten2** [comment]
@romatroskin Make sure you only have the `'OneSignal'` pod in your `OneSignalNotificationServiceExtension` in your `Podfile`. Also please make sure to always open the new `<project-name>.xcworkspace` file instead of the `<project-name>.xcodeproj` file.
Please double check all instructions noted in the `2. Import OneSignal into your Xcode project` section of the OneSignal Flutter setup guide.
https://documentation.onesignal.com/docs/ios-sdk-setup#section-2-import-one-signal-into-your-xcode-project

Please provide more details if you are still stuck.

`OneSignalNotificationServiceExtension` is required for a number of notification features, however if you only need to send basic text only notifications you could build your project without it to get by.

**Comment by duduBaiao** [comment]
That was happening for me in a Flutter project (created 1 year ago) when I tried to build with the last Xcode.

This answer solved the problem:
https://stackoverflow.com/a/54704516
