### ISSUE TITLE
Example Project - Check failed: vm. Must be able to initialize the VM.

### ISSUE THREAD

**Issue by egeneration-me** [OneSignal/OneSignal-Flutter-SDK#215]
**Description:**

Got this error at Release mode:

2020-03-02 10:20:41.192470-0500 Runner[3886:2503775] [VERBOSE-2:dart_vm.cc(241)] Could not setup VM data to bootstrap the VM from.
2020-03-02 10:20:41.192505-0500 Runner[3886:2503775] [VERBOSE-2:dart_vm_lifecycle.cc(84)] Could not create Dart VM instance.
2020-03-02 10:20:41.193042-0500 Runner[3886:2503775] [VERBOSE-3:shell.cc(234)] Check failed: vm. Must be able to initialize the VM.

Hi, there:

I just download your example, and change Generated.xcconfig file from 
FLUTTER_FRAMEWORK_DIR=/.../flutter/bin/cache/artifacts/engine/ios
to 
FLUTTER_FRAMEWORK_DIR=/.../flutter/bin/cache/artifacts/engine/ios-release

then I use pod install, then change the XCode Bundle identifier, when I run at Physical iPhone, I got crash.

but I debug mode is OK, 

**Environment**

OneSignal Flutter SDK version is 2.3.4

**Steps to Reproduce Issue:**

 just download your example, and change Generated.xcconfig file from 
FLUTTER_FRAMEWORK_DIR=/.../flutter/bin/cache/artifacts/engine/ios
to 
FLUTTER_FRAMEWORK_DIR=/.../flutter/bin/cache/artifacts/engine/ios-release

Run at  Physical iPhone

(crash stacktraces, as well as any other information here)

**Comment by jkasten2** [comment]
@egeneration-me Thanks for reporting. It may just be an issue with the setting in our example project as I don't see anything that bring up OneSignal in the error. Are you seeing this issue in your project or in a new project?

Can you provide the following details so we can reproduce as well?
1. Flutter version
2. Xcode version
3. By "Release mode" do you mean building an .ipa from Xcode? Or simply just running from Xcode instead of Android Studio to an iOS device?

**Comment by rgomezp** [comment]
Closing due to no response
