### ISSUE TITLE
permision for huawei protected app

### ISSUE THREAD

**Issue by mamonraab** [OneSignal/OneSignal-Flutter-SDK#266]
**Description:**
 
hello  , one signal not show any ask for permision to add the app in   the huawei protected app  , since there is alot of huawei devices and  app cant for example get push notification  if it not added to huawei protected app

(your description here)

**Environment**
flutter 1.17  , onesignal 2.5

 i dont know  if these issuse of feature request but same as there is a setting for IOS to ask for permision  there must be setting for such cases  to ask for permision once app opend

**Comment by jkasten2** [comment]
@mamonraab 

## New Huawei Devices
### HMS Notification Message Type
For all new Huawei devices which now do not have Google Play services the huawei protected / power saving app is no longer an issue. This is due to OneSignal now supporting Huawei's HMS push and their "Notification Message" type which means the app doesn't have to be started the display the notification.
See the [OneSignal Huawei Flutter SDK Setup](https://documentation.onesignal.com/docs/huawei-flutter-sdk-setup) on setting this up to make sure you support push for these devices.

## Older Huawei devices
### Uses FCM when Available
For older Huawei devices that still have Google Play services installed may have this issue depending on the specific device and default settings on the device since pushes it will go through FCM.

### Official API for Huawei protected / battery app
I was not able to find any official documentation on prompting for permission for this. I don't believe this something built into Huawei ROMs to prompt for this.

Someone did ask this question on Huawei's Forums but it is still unresolved.
https://forums.developer.huawei.com/forumPortal/en/topicview?tid=0201233623800480077&fid=0101187876626530001

### Possible Workaround
https://stackoverflow.com/questions/31638986/protected-apps-setting-on-huawei-phones-and-how-to-handle-it

**Comment by mamonraab** [comment]
yes i did notice the HMS of new devices but the old devices was my concern
thanks for your help

**Comment by mamonraab** [comment]
also i did see some apps propet the user for allowing the app to go in protacted  , the https://stackoverflow.com/questions/31638986/protected-apps-setting-on-huawei-phones-and-how-to-handle-it

 is not a good one
while relying on  the onesignal to ask for such permision i think is the best option

many thanks
