### ISSUE TITLE
How can i choose what notifications show to the user?

### ISSUE THREAD

**Issue by joaoarmando** [OneSignal/OneSignal-Flutter-SDK#297]
Hello, I have a particular situation here. My app needs to show to the user the only last "notification" received for a thread.

Imagine the following notifications received, where we have two groups, Group A and Group B.

 - **Group A**
    - Hello, dear! _(first notification received)_
    - Let's talk about our project. (last notification received)
 - **Group B**
    - Do you like red or white? (_since this is the only notification received witch is related to Group B, this is the "last" notification received in this thread.)_

 I need to show only the last notification received from both groups. In that case, I need to show: 
  - Let's talk about our project. **(Last received related to group A)**
  - Do you like red or white? **(Last received related to group B)**

If the user has no internet connection he will receive all notifications witch was sent to him when he was offline. I want to avoid it, by showing only the last notification received from each group.

There is a way to receive notifications from OneSignal and choose how notification show?

**Comment by uj** [comment]
The problem is that once you send a notification and it goes to Apple/Google, it is then out of your control.  You can set the expiration time before you send it, which isn't really ideal.  You would still be missing the last one sometimes and getting more than just the last one sometimes.

Your question is almost equal to the following scenario:

I want to mail a lot of letters through the post office to someone, but I only want them to receive the last letter sent if they are not at home so they don't come home to a pile of letters.

Another issue is:  how do you know which message is the last one?  How do you know there won't be another message sent after "Do you like red or white".  What if, 10 minutes later, group B writes "or what about green".

You will need a lot of logic within your app to even begin to do what you are wanting.

**Comment by joaoarmando** [comment]
I don't need to wait a lot of seconds, It just happens when the user was offline and then they connect to the internet. A simple timer of 5 seconds delay wich any new notifications from its thread restart the timer. At the end of the timer i show the notification to user.

My app will not send a lot of notifications to the user, it isn't like message apps but maybe notifications can pop up with an interval of 15 minutes or more. In that case, if the user became offline for 1 hour and I sent to him a notification every 15 minutes when he connects to the internet he will see 4 notifications. So I just want to show the last notification that he received.

**Comment by uj** [comment]
I'm not sure that is going to be possible.  You would have to know before you sent the message if the user is online or not, and there isn't a good way to know that.  Once you send the message, it is impossible to cancel it (other than presetting an expiration on it, but then you risk missing all messages including the last message).

**Comment by joaoarmando** [comment]
Do you know if i can avoid a notification to pop up?

**Comment by joaoarmando** [comment]
I'll be able to fix it by using "collapse_id" parameter.
