### ISSUE TITLE
When i navigate to other screen am getting context null in my main.dart

### ISSUE THREAD

**Issue by prakash6491** [OneSignal/OneSignal-Flutter-SDK#376]
Exactly am getting this error in my log 
Exception has occurred.
FlutterError (Navigator operation requested with a context that does not include a Navigator.
The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.)

```
` OneSignal.shared.setNotificationOpenedHandler(
          (OSNotificationOpenedResult result) async {
        // will be called whenever a notification is opened/button pressed.
        // int feedId =
        // await result.notification.payload.additionalData["notification_id"];
        Future.delayed(Duration(milliseconds: 10), () {
          // Do something
          Navigator.pushReplacement(
            context,
            new MaterialPageRoute(builder: (context) => new DetailScreen()),
          );
        });

```
```

```
```

**Comment by phcs971** [comment]
You have to set a navigator in your MaterialApp(), save it in an external variable/class/service and use that key to get the context 

Creating the key:
`final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();`

Setting the key:
`MaterialApp(
    navigatorKey: navigatorKey,
    ...
),`

Using the key:
`
//Change this
Navigator.pushReplacement(
    context,
    new MaterialPageRoute(builder: (context) => new DetailScreen()),
);
//To this
navigatorKey.currentState.pushReplacement(MaterialPageRoute(builder: (_) => DetailScreen()));
`

I recommend using named routes instead of passing the widget in the MaterialPageRoute, also to save the navigatorKey in a class/service is good to use a lib like GetIt to generate singletons.

The lib get ([https://pub.dev/packages/get](https://pub.dev/packages/get)) does all of this for you, just change the MaterialApp to GetMaterialApp and call
`Get.to(DetailScreen())`

**Comment by prakash6491** [comment]
thank  you much ..now its working .
