### ISSUE TITLE
Multiple Websites, Seperate Notification switch with 1 Onesignal app id

### ISSUE THREAD

**Issue by Gunawan888** [OneSignal/OneSignal-Flutter-SDK#448]
Hi All, 

I have been looking into One Signal documentation. Pretty sure we are only able to initialise only 1 onesignal app id in a flutter app? If thats the case,  the problem is my app contain the 3 websites (Say Website A, B, C) and they are all using the same onesignal app id as a result of that restriction. 

So currently, my app only have one switch to turn on/off the notification from all the websites. What I want to do is to create 3 seperate switches for each website. So switch A will be for website A, Switch B will be for website B, and so on.  Is it possible? Look forward to hear something. Thanks for your help :).

**Comment by emawby** [comment]
@Gunawan888 I am not sure I fully understand your desired site setup, but I believe the origin of the website needs to be different across sites A, B, and C in order to use different App IDs for each. I don't believe that we currently support your setup. 

You might be able to approximate it by using [segments](https://documentation.onesignal.com/docs/segmentation) and having different segments for each of the three sites.

**Comment by DavidG4869** [comment]
Hi @emawby 

Thanks for getting back to me. A bit background to the apps: It's a centralized app contain blog posts from three websites (A, B, and C). We want to make thee post notification switches (on/off) for each sites as they have different audience/target. I have no desired setup as long as the above use case is fulfilled (whether using one shared one signal app id or 3 one signal app id).

Initially, I want to make each of them have separate Onesignal instance (Distinct app id as a result). But I think at the moment 1 flutter app can only initialize 1 app id? Just wondering if it's possible for my app to have  3 onesignal app id (so one each for each sites). That way each website/instance will be able to setNotification(true/false) their own. Please let me know

**Comment by emawby** [comment]
@DavidG4869 We currently do not support multiple App IDs unfortunately. 

My idea with the segments is to have a segment (group of users) for each site. You could do this using our [Data Tag functionality](https://documentation.onesignal.com/docs/add-user-data-tags). The idea being that you create the 3 switches you mentioned where if a user toggles the switch for Site X then you add a tag for that user indicating that they want to receive notifications for that Site. 
Then you can create a segment that includes all users that have that tag.

So "Toggle A" sets data tag -> "Site A". 
"Segment A" uses logic to include all users with data tag "Site A".

Repeat for sites B and C.

Then you can target your push notification to Segment A, B, and C as appropriate.

**Comment by DavidG4869** [comment]
@emawby Thanks for this. Last question, my source sites are wordpress sites and using onesignal plugin. The problem is how do I target specific segment for each website every time I published a new post? (i.e Website A will send post notification to segment 'Website A')?

**Comment by rgomezp** [comment]
Howdy, 
The plugin doesn't support this feature currently. It simply sends to all subscribers of that website each time you post with the checkbox.

If you would like to use segmentation, you will have to modify the plugin itself to include the segments you want to target. This can be done in the `onesignal-admin.php` file by including the segment you need in `$fields` (https://github.com/OneSignal/OneSignal-WordPress-Plugin/blob/main/onesignal-admin.php#L840)

Remember that you will also need to tag each user with the correct values in order to segment them properly.

Hope this helps. Enjoy!
