### ISSUE TITLE
OSiOSSettings.inAppLaunchUrl is deprecated ??? What??

### ISSUE THREAD

**Issue by achalkias** [OneSignal/OneSignal-Flutter-SDK#539]
Greetings how can i implement the following after the 3.0.0 upgrade ???

```dart
 OneSignal.shared.init(
        mOneSignalAppId,
        iOSSettings: {OSiOSSettings.autoPrompt: true, OSiOSSettings.inAppLaunchUrl: true,OSiOSSettings.inFocusDisplayOption: OSNotificationDisplayType.notification});
```

In this link
https://documentation.onesignal.com/v7.0/docs/step-by-step-flutter-2x-to-300-upgrade-guide
it says that `OSiOSSettings.inAppLaunchUrl` is deprecated. There is currently no replacement for it.

But i really need my app to open to browser when the notification has a web url. Any suggestions? or am i missing something here?

Thanks in advance.

**Comment by jkasten2** [comment]
@achalkias There are two options available.

1. You can use [`OneSignal_suppress_launch_urls`](https://documentation.onesignal.com/docs/links#launch-url) to disable the OneSignal SDK from handling the opening of the launch URL and can direct the user based on your own logic.
2. Instead of using launch URL you can set your URL in additional data and use logic in your app to handle directing your users.

**Comment by jkasten2** [comment]
Thanks for letting us know about the work around. We have added `setLaunchURLsInApp` in the [3.3.0 release](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/3.3.0) so you can call this directly from dart without having to set native code now.
