### ISSUE TITLE
Cannot access io.flutter.plugin

### ISSUE THREAD

**Issue by bhrayhaw** [OneSignal/OneSignal-Flutter-SDK#541]
Need help

error: error reading C:\Users\ADMIN\.gradle\caches\modules-2\files-2.1\androidx.lifecycle\lifecycle-common-java8\2.2.0\cd3478503da69b1a7e0319bd2d1389943db9b364\lifecycle-common-java8-2.2.0.jar; zip END header not found
C:\Users\ADMIN\StudioProjects\newflutterapp\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:1: error: cannot access io.flutter.plugins
package io.flutter.plugins;
^
  zip END header not found
C:\Users\ADMIN\StudioProjects\newflutterapp\build\app\generated\source\buildConfig\debug\com\example\newflutterapp\BuildConfig.java:4: error: cannot access com.example.newflutterapp
package com.example.newflutterapp;
^
  zip END header not found
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by nan-li** [comment]
Hi @bhrayhaw,

I don't see that this is a `OneSignal` error. It looks like both of these errors are due to `zip END header not found`, and it's hard to know what might be causing this for your specific case.

I recommend searching for that error and troubleshooting from there. Maybe you can try deleting your `.gradle` folder as a first step (https://github.com/flutter/flutter/issues/73852#issuecomment-759494547).

**Comment by bhrayhaw** [comment]
I have gotten it now
