### ISSUE TITLE
One Signal Error 400 When Using Function setSMSNumber

### ISSUE THREAD

**Issue by minhkimlong** [OneSignal/OneSignal-Flutter-SDK#558]
## What
One signal error when using setSMSNumber

## Why
I do not understand why when I use setSMSNumber from one signal I have this error ?

## Image
<img width="557" alt="Screen Shot 2022-05-25 at 19 07 44" src="https://user-images.githubusercontent.com/36654067/170258558-fa117bcd-2632-4a19-8b21-45a8bb807073.png">

<img width="1281" alt="Screen Shot 2022-05-25 at 19 07 55" src="https://user-images.githubusercontent.com/36654067/170258585-c46f4643-7ded-4e08-b202-e55baba831ea.png">

**Comment by jkasten2** [comment]
@long-joecoffee Can you try calling `OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none);` before this and provide all log entries before this error?

Also do you see this issue on only iOS?, or Android as well?

**Comment by long-joecoffee** [comment]
I will make a video for you

**Comment by long-joecoffee** [comment]
## The first time when the app run firstly that i want to init one signal
<img width="627" alt="Screen Shot 2022-05-27 at 13 57 15" src="https://user-images.githubusercontent.com/36654067/170647782-e54ece26-85bc-4ee3-9e35-10d2630d0584.png">

## After this func execute will run after the user logins successfully
<img width="627" alt="Screen Shot 2022-05-27 at 13 57 27" src="https://user-images.githubusercontent.com/36654067/170648164-f7840b57-670b-4ed4-bd8b-574110637cb3.png">

## I still do not understand why this error logs in here, because if something is wrong with function "execute" it will log in the catch scope, but for now it logs this error in function runGuard when the user login successfully
<img width="576" alt="Screen Shot 2022-05-27 at 13 57 04" src="https://user-images.githubusercontent.com/36654067/170648514-cedc7b4a-23da-49d2-abe0-49ca029341a9.png">

**Comment by long-joecoffee** [comment]
I try to remove setLogLevet but this bug still happens

**Comment by long-joecoffee** [comment]
I look around where I use setLevelLog, but 1 in the example of the one signal, and other is in one signal service, I try to remove but this bug is still there
<img width="869" alt="Screen Shot 2022-05-27 at 18 19 55" src="https://user-images.githubusercontent.com/36654067/170690149-a3730145-a309-4ab7-a58f-ceef74980ef2.png">

**Comment by long-joecoffee** [comment]
I try to debug, the first time logins failed but the second time is successfully, I do not understand why -(
<img width="1351" alt="Screen Shot 2022-05-27 at 18 58 20" src="https://user-images.githubusercontent.com/36654067/170695122-07afd312-2349-476d-b498-b9347e829491.png">

**Comment by nan-li** [comment]
Hi @long-joecoffee,

There is no need to remove `setLevelLog`, and it is not causing this error. You can remove `setLevelLog` if you want to **stop** debugging.

Instead, keep `OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none)` because it will give us more information in the logs.

Unfortunately, Flutter's `PlatformException` doesn't include much detail.
```
PlatformException(400, The operation couldn’t be completed. (OneSignalError error 400.), null, null)
```

With `OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none)` set, there should be more information showing what the native iOS SDK is doing (network calls, etc.). This information is needed to figure out what the error actually is.

**Comment by nan-li** [comment]
Hi @long-joecoffee,

Are you still experiencing this problem?
Please keep this line in your code: `OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none)`. Then, check the logs in Android Studio. 

Unfortunately, Flutter's logs don't have good information, but if you check the logs in Android Studio, there should be some more information about the 400 error.

**Comment by darwin-morocho** [comment]
I have the same error

**Comment by long-joecoffee** [comment]
OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none), I used to be add this code and the bug still happen. So the reason isn't the setLogLevel func

**Comment by long-joecoffee** [comment]
The reason here. I know why when the first time I just CALL the func setSMSNumber, the 400 erro happens, and I try to call again it's not happens the 400 error.

**Comment by long-joecoffee** [comment]
Thank you so much nan-li, but the first thing I use is the same phone number. the first time the 400 error appears and the second time doesn't appear.

**Comment by long-joecoffee** [comment]
When I use this OneSignal.shared.setLogLevel(OSLogLevel.verbose, OSLogLevel.none) or not using the log func is still the same image below:
<img width="810" alt="Screen Shot 2022-07-22 at 06 24 25" src="https://user-images.githubusercontent.com/36654067/180331121-1b8c247c-1bcd-489c-af68-8321081048be.png">

**Comment by long-joecoffee** [comment]
And for more in the text field, we do the validate only apply the number, not the text.

**Comment by nan-li** [comment]
@long-joecoffee Ahhh I think it is because you are looking at the `console`, only Dart `print()` will be displayed. Native iOS logs will not show. Can you run the app in a Terminal, with `flutter run` ([using flutter command line](https://docs.flutter.dev/reference/flutter-cli)). The Terminal should show the native iOS logs as well.

![IMG_7981](https://user-images.githubusercontent.com/4022291/180332261-d8a561c7-984b-4be8-b8c5-f0bd8b769bb9.jpg)

**Comment by long-joecoffee** [comment]
oh wow, thank you so much, I will let you know later

**Comment by emawby** [comment]
Closing this issue as stale. If it is still a problem in tag me and I can reopen.
