### ISSUE TITLE
Set External Id Not Working

### ISSUE THREAD

**Issue by kwameopareasiedu** [OneSignal/OneSignal-Flutter-SDK#589]
**Description:**

In the v3.4.1 version of the SDK, calling the `OneSignal.shared.setExternalUserId(id)` does not seem to work. It logs successfully in the emulator console but when I checked my user in the dashboard, the external id field is still blank. As such API calls to send a notification return the following error:

```
{
  id: '',
  recipients: 0,
  errors: [ 'All included players are not subscribed' ]
}
```

**Environment**
1. Onesignal_Flutter 3.4.1
2. Installed using `flutter pub add`

**Steps to Reproduce Issue:**
1. Use `flutter create` to create a new project
2. Install the latest version of `onesignal_flutter`: 3.4.1
3. Make a call to `OneSignal.shared.setExternalUserId(id)`
4. Check value of external user id in dashboard

**Anything else:**
Below are the logs when the `setExternalUserId(id)` is called:
```
D/OneSignal(10812): UserStateSynchronizer internalSyncUserState from session call: false jsonBody: {"external_user_id":"<ID here>","app_id":"<ID here>"}
D/OneSignal(10812): OneSignalRestClient: Making request to: https://api.onesignal.com/players/<ID here>
D/OneSignal(10812): OneSignalRestClient: PUT SEND JSON: {"external_user_id":"<ID here>","app_id":"<ID here>"}
V/OneSignal(10812): OneSignalRestClient: After con.getResponseCode to: https://api.onesignal.com/players/<ID here>
D/OneSignal(10812): OneSignalRestClient: Successfully finished request to: https://api.onesignal.com/players/<ID here>
D/OneSignal(10812): OneSignalRestClient: PUT RECEIVED JSON: {"success":true}
V/OneSignal(10812): Completed request to update external user id for channel: push and success: true
V/OneSignal(10812): External user id handlers are still being processed for channel: push , wait until finished before proceeding
V/OneSignal(10812): Completed request to update external user id for channel: push and success: true
```

**Comment by nan-li** [comment]
Hi @kwameopareasiedu,

Thank you for reporting. Can you answer some clarifying questions:

1. Does the external ID eventually show up in the dashboard after waiting some time and checking again? 
2. Does this also happen on iOS?
3. Does this consistently happen or does it work sometimes?

**Comment by kwameopareasiedu** [comment]
Hello @nan-li ,

1. Yes, it did appear on the dashboard after a while
2. I haven't tested on iOS yet
3. Well, this is the first time I'm experiencing it. After the external id appeared that time, I haven't encountered this issue on subsequent fresh installs

**Comment by nan-li** [comment]
Hi @kwameopareasiedu,

You mentioned in your last response that you haven't encountered this issue after that time.

I am checking in if that is still true, or is this still an issue for you?

**Comment by kwameopareasiedu** [comment]
Safe to say, this is no longer an issue...

**Comment by Princewil** [comment]
@nan-li can you pls tell me what you did because I currently facing this issue.

the external UID reflects on the onesignal console, but when I send notifications using the uid it say “players not subscribed”, however sending with the default uid go successfully. 

Thank you

**Comment by RogerBrusamarello** [comment]
Any updates here?

**Comment by SvetoslavStefanov** [comment]
> Any updates here?

OneSignal's documentation is **terrible**!  

I had an older project that worked just well and wanted to use oneSignal on my newest project. But everything has changed since then and there are missing things, which are not explained at all.

I believe the method `.setExternalUserId` has been replaced with `OneSignal.login("useremail@gmail.com");`. After calling this method it adds this as an externalId to my user in OneSignal's Dashboard.

If you want to get your user's subscription id: `OneSignal.User.PushSubscription.id`

Adding emails now is done via `OneSignal.User.addEmail("customer@company.com");`
Adding phone is done via `OneSignal.User.addSms("+15558675309");`

adding custom tags:
`        const tags = {
         KEY_01: "VALUE_01",
         KEY_02: "VALUE_02",
         KEY_03: "VALUE_03"
        };
        OneSignal.User.addTags(tags);`

Are notifications supported: `const isSupported = OneSignal.Notifications.isPushSupported();`

Listening to events:
`
OneSignalDeferred.push(function (OneSignal) {
OneSignal.User.PushSubscription.addEventListener("change", function (event) {`

Hope this helps you

**Comment by nan-li** [comment]
Hi @Princewil and @RogerBrusamarello, since so long has passed, please open a new issue with the details of your report.
