### ISSUE TITLE
sendTag throws errors

### ISSUE THREAD

**Issue by NikosTsesmelis** [OneSignal/OneSignal-Flutter-SDK#605]
### What happened?

I keep getting these 2 errors:

PlatformException(0, The operation couldn’t be completed. (OneSignalError error 0.), null, null). Error thrown null.
Non-fatal Exception: FlutterError
0  ???                            0x0 StandardMethodCodec.decodeEnvelope + 653 (message_codecs.dart:653)
1  ???                            0x0 MethodChannel._invokeMethod + 296 (platform_channel.dart:296)
2  ???                            0x0 OneSignal.sendTags + 243 (onesignal_flutter.dart:243)
3  ???                            0x0 OneSignal.sendTag + 233 (onesignal_flutter.dart:233)

PlatformException(OneSignal, Encountered an error updating tags (-1): Unable to update tags: the current user is not registered with OneSignal, null, null). Error thrown null.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:296)
       at OneSignal.sendTags(onesignal_flutter.dart:243)
       at OneSignal.sendTag(onesignal_flutter.dart:233)

### Steps to reproduce?

```Markdown
calling OneSignal.shared.sendTag
```

### What did you expect to happen?

not getting these errors

### OneSignal Flutter SDK version

3.4.1

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gagandeep-nickelfox** [comment]
Same thing happened to me, any luck finding solution?

**Comment by jennantilla** [comment]
Hello everyone, apologies that this issue has gone stale. I'm going to close it due to inactivity.

We have released major updates to the [Flutter SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5) which includes many improvements and enhancements. Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details!

If you are still having issues after upgrading, please open a new issue and we'll be happy to investigate further!
