### ISSUE TITLE
[question]: OneSignal Large Icon Error

### ISSUE THREAD

**Issue by alishahzad331** [OneSignal/OneSignal-Flutter-SDK#612]
### How can we help?

In debug mode, the app shows  large icon from the app/src/main/res/drawable folder in the project. But it shows black square image in the release mode.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello there! Apologies that this issue was missed. I'm going to close due to inactivity but if you are still having issues with the large icon, please let us know!

We have released major updates to the [Flutter SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5) which includes many improvements and enhancements. Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details!

**Comment by chandabdullah** [comment]
large icon showing on Emulator fine! but showing black square on real device 

![WhatsApp Image 2024-05-16 at 11 59 28](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/162584437/87c86427-db51-4654-aac3-b4c4cee8999a)
