### ISSUE TITLE
[Bug]: can't logout email with external user Id

### ISSUE THREAD

**Issue by LukasMys** [OneSignal/OneSignal-Flutter-SDK#625]
### What happened?

I set an externalUserId and email when I log in a user. During logout email, sometimes i get error: "status code: 400; errors: ["identifier must exist for email"]". before logging out, it is checked whether `emailAddress` and `emailUserId` are not null. 
 In addition request is sinding a few times but method is invoking once.
 If it metters - order of execution methods:
 1. Login:
  a. set External User Id
  b. set Email
 2. Logout:
  a. logoutEmail()
  b. remove External User Id
  

![image](https://user-images.githubusercontent.com/118441756/206669940-e29889fe-d8e4-419e-8cfe-9285c23e7d6e.png)

 

### Steps to reproduce?

```Markdown
Login and logout a few times to reproduce. Usually 3-7 times is enough.
```

### What did you expect to happen?

I expected the logout email should logging out when email and email id is not empty.

### OneSignal Flutter SDK version

3.5.0

### Which platform(s) are affected?

- [ ] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@LukasMys apologies that this issue was missed.

We have released major updates to the [Flutter SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5) which includes many improvements and enhancements. Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details!

If you are still having issues after upgrading, please create a new issue and we'll be happy to assist!
