### ISSUE TITLE
[Bug]: Previous received notification is showing up again when app is opened next time.

### ISSUE THREAD

**Issue by Jos-Sea** [OneSignal/OneSignal-Flutter-SDK#636]
### What happened?

I dismissed the notification I received from the notification panel but the same dismissed notification appeared again when the app was opened. And was also showing the notification received past time. Example as 5h.

### Steps to reproduce?

```Markdown
1. when notification receive dismiss from notification panel
2. close the app and don't use it for some time
3. open the app again
4. now will see the previous dismissed notification is showing up again.
```

### What did you expect to happen?

The expected result should be dismissed notification should not show again when user open the app next time.

### OneSignal Flutter SDK version

3.3.2

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brismithers** [comment]
Hi @Jos-Sea , I haven't been able to reproduce this unfortunately.  Can you confirm this is both an Android *and* an iOS issue?

**Comment by Jos-Sea** [comment]
Hi @brismithers, The issue has only been confirmed to reproduce on the Android platform.

**Comment by alabiboo** [comment]
Hi @Jos-Sea , I have the same problem. did you find a solution that could help me too?

**Comment by NOTtheKRish** [comment]
Hello @Jos-Sea , I too have the same problem... Is there any solution to solve this??

**Comment by jennantilla** [comment]
Hello there everyone! Apologies that this issue has gone stale. Since the original report of this problem, we have released a new version of our SDK with many improvements and enhancements. Please update to our [latest release](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.2.6) (see [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md)) and if you are still having any trouble, we encourage you to open a new ticket so we can renew investigation. Thanks!
