### ISSUE TITLE
[question]: Error "Identifier invalid format" on set sms number

### ISSUE THREAD

**Issue by AurelVU** [OneSignal/OneSignal-Flutter-SDK#663]
### How can we help?

Hello. I try to set phone after my user authorized, but I get error:

VERBOSE: HTTP Request (OSRequestUpdateDeviceToken) with URL: https://api.onesignal.com/players/b--------f-8--0-4--1-a--5-6------------fb, with parameters: {
  "app_id" : "38---------------------e",
  "identifier" : "+79002008008"
}
VERBOSE: network response (OSRequestUpdateDeviceToken): {
    errors =     (
        "[\"Identifier invalid format.\"]"
    );
    success = 0;
}

I hid some of the identifiers for security reasons and changed a few digits in the number, but kept the original format.
This problem is reproduced exclusively when authorization is performed, in the middle of the application's life. The same procedure at the start of the application is successful. What am I doing wrong?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @AurelVU,

First, SMS numbers must follow E.164 format of `[+][country code][number including area code]`, which it looks like you have correctly. Confirm that it is always sent in this format.

When you say "This problem is reproduced exclusively when authorization is performed", is this your own authorization unrelated to OneSignal? Or are you referring to [OneSignal's Identity Verification](https://documentation.onesignal.com/docs/identity-verification)?

**Comment by jennantilla** [comment]
Closing due to no response.
