### ISSUE TITLE
[Bug]: iOS OneSignal does not start

### ISSUE THREAD

**Issue by chrisvidal** [OneSignal/OneSignal-Flutter-SDK#672]
### What happened?

using the latest OneSignal: 3.5.1

It works fine on Android.
the framework does not even start on iOS.

when using the simulators, I can see trace from OneSignal in the output log when testing on Android.
But there is no output log when testing on the iOs Simulator, it does not register any externalUserId as well.

Thank you so much for any assistance

### Steps to reproduce?

```Markdown
following the documentation
```

### What did you expect to happen?

expecting to see the framwork onesignal starting on ios

### OneSignal Flutter SDK version

3.7.7

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
while running on Android, I can see this output log

V/OneSignal( 4303): Initializing the OneSignal Flutter SDK (3.3.2)
```
that I dont see with iOS.
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

<!-- probot = {"onesignal-probot":{"response_time_in_business_days":17}} -->

**Comment by lord-tx** [comment]
What iOS version are you testing this on? This is based on tests that iOS Simulator versions <= 15 do not work with Push Notifications.

**Comment by emawby** [comment]
@chrisvidal Hello what log level are you using? Can you also show your iOS podfile?

**Comment by jennantilla** [comment]
Closing due to no response. @chrisvidal if you are still having problems please submit a new issue and we'll be happy to take a look!

We have released major updates to the [Flutter SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5) which includes many improvements and enhancements. Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details!
