### ISSUE TITLE
No documentation on postnotificationWithJson

### ISSUE THREAD

**Issue by QuantumLabsTz** [OneSignal/OneSignal-Flutter-SDK#676]
I'm trying to send notification with postNotificationWithJson but there is no documentation on this function no examples. The biggest issue is the header and body. A simple example will help. This function is best because I can filter or use segments compared to osNotification which requires only playerIDs

**Comment by jennantilla** [comment]
Hello @QuantumLabsTz apologies that this question was missed. I'm going to close this issue since it's gone stale.

We have dropped the `postNotification` / `postNotificationWithJson` methods from our [latest User Model SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5). 

You can continue to use our REST API to send out the Push, however - due to security risks for your REST API key, we do advise you to create an API to your backend and make the request from your backend instead of directly from your mobile app.
​
For more details please refer to the below document:
​https://documentation.onesignal.com/reference/create-notification

Please let us know if you have any further questions or concerns!
