### ISSUE TITLE
[question]: How to enable confirmed delivery

### ISSUE THREAD

**Issue by YanivYon** [OneSignal/OneSignal-Flutter-SDK#687]
### How can we help?

Hi
the package is working fine.
Confirmed Delivery is working fine on iOS but we don't get any values for Android.
Please help

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @YanivYon apologies that your question was missed. Since this issue has gone stale, I'm going to close it out.

Please see our [Confirmed Delivery troubleshooting docs](https://documentation.onesignal.com/docs/confirmed-delivery#confirmed-delivery-troubleshooting) for more information on issues with Confirmed Delivery. Specifically on Android, it may be the case where the [app is force-quit](https://documentation.onesignal.com/docs/confirmed-delivery#android-devices-force-quitting-the-app).

If you are still having any problems, please submit a new issue and we'll be happy to dive deeper!
