### ISSUE TITLE
OneSignal.shared.setNotificationWillShowInForegroundHandler

### ISSUE THREAD

**Issue by wbasabe0891201** [OneSignal/OneSignal-Flutter-SDK#690]
### What happened?

When a notification is send (and received) and the application is open the **OneSignal.shared.setNotificationWillShowInForegroundHandler** should be always executed but not alwalys is.

The notification is received with no problem.

### Steps to reproduce?

```Markdown
In the main method before the **runApp** it is run in  the folloeing order:
await OneSignal.shared.setAppId(onesignalAndroidId);
OneSignal.shared.setNotificationOpenedHandler((OSNotificationOpenedResult result) {
    ...
});

OneSignal.shared.setNotificationWillShowInForegroundHandler((OSNotificationReceivedEvent event) {
    ...
});
...
runApp(const MyApp());
```

### What did you expect to happen?

I expected to **OneSignal.shared.setNotificationWillShowInForegroundHandler** always be executed since it is implemented.

### OneSignal Flutter SDK version

3.5.1

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @wbasabe0891201 apologies that this issue was missed. Are you still having this issue? If so, can you please provide the full log from the device reproducing this behavior?

I'd highly suggest upgrading to our lates major release of the [Flutter SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5) which includes many improvements and enhancements. Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details!

**Comment by jennantilla** [comment]
Closing due to no response.
