### ISSUE TITLE
[Bug]: OneSignal.sendTags FlutterError - PlatformException(0, The operation couldn’t be completed. (OneSignal Error error 0.), null, null)

### ISSUE THREAD

**Issue by vqthanh1412489** [OneSignal/OneSignal-Flutter-SDK#697]
### What happened?

I got this crash on the Firebase Crashlytics dashboard when sent a tag with the method:
```OneSignal.sendTags```

### Steps to reproduce?

```Markdown
1. Implement One-Signal in your app
2. Use .sendTags to send the tag of your devices.
3. Wait some time I have this error on the Firebase Crashlytics dashboard
```

### What did you expect to happen?

I do not see this error Firebase Crashlytics dashboard or when it's happening 

and if I got this error, What will happen after that?

### OneSignal Flutter SDK version

onesignal_flutter: ^3.5.0

### Which platform(s) are affected?

- [X] iOS
- [X] Android

### Relevant log output

```Shell
PlatformException(400, The operation couldn’t be completed. (OneSignalError error 400.), null, null)

or

PlatformException(500, The operation couldn’t be completed. (OneSignal Error error 500.), null, null)

message_codecs.dart - Line 652
StandardMethodCodec.decodeEnvelope + 652

platform_channel.dart - Line 310
MethodChannel._invokeMethod + 310

2
onesignal_flutter.dart - Line 243
OneSignal.sendTags + 243

onesignal_flutter.dart - Line 233
OneSignal.sendTag + 233
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
@vqthanh1412489 apologies that your issue was missed. Are you still having problems? 

If so, can you please share how and when you are calling the `sendTag` method?

Please also note that we have released major updates to the [Flutter SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5) which includes many improvements and enhancements. In 5.0.0 SDKs and higher, the new method is `addTag`. 

Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details.

Thanks!

**Comment by jennantilla** [comment]
Closing due to no response.
