### ISSUE TITLE
[question]: How can I change the Subscription Status?

### ISSUE THREAD

**Issue by maiconkf** [OneSignal/OneSignal-Flutter-SDK#704]
### How can we help?

After uninstalling the application and reinstalling it, my user status is "Not Subscribed," and I'm unable to change the status.

Code:

`onesignal_flutter: ^3.5.1`

```
  @override
  void initState() {
    super.initState();

    OneSignal.shared.setAppId("APP_ID");
    OneSignal.shared.promptUserForPushNotificationPermission();
    OneSignal.shared
        .setNotificationOpenedHandler((OSNotificationOpenedResult result) {
      print(result.notification.templateName);
      _createAppOpenAd();
    });
  }
 ```
 
 
<img width="1420" alt="image" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/5395835/94b0ec28-9e32-4759-b54c-5c2c5707bbc8">

What am I doing wrong?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkasten2** [comment]
@maiconkf The "Not Subscribed" status has a few different causes, a more common one is a push token was not give to the device by FCM.

Can you view the logcat to see if you get any errors on the device? Feel free to share it here and we can take a look.

_5.x.x version of this "Not Subscribed" issue: #826_

**Comment by jennantilla** [comment]
Closing due to no response.

@maiconkf, we have released major updates to the [Flutter SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.1.5) which includes many improvements and enhancements. Please refer to our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md) for full details.

If you are still having issues after upgrading, please let us know in #826.

Thanks!
