### ISSUE TITLE
[Bug]: OneSignal Flutter notification open handler (iOS) issue in 3.5.0.

### ISSUE THREAD

**Issue by hamzasharif1199** [OneSignal/OneSignal-Flutter-SDK#739]
### What happened?

In Flutter one signal version 3.5.0 setNotificationOpenedHandler is not working. When click on notification it opens the app but this function is not working and we can perform any further action regarding this function. Can you fix it as soon as possible somebody reported it before but the issue is still open and not fixed.

Kindly fix it as soon as possible. I will be looking forward to your response.
hopefully, it will be a positive one.

### Steps to reproduce?

```Markdown
1. Install app 
2. the app is launched.
3. setNotificationOpenedHandler is not working as expected because it's not performing any action.
4. Not even showing in console anything.
```

### What did you expect to happen?

I expect to navigate the same as in the Android. it's working great on android but in ios its not working.

### OneSignal Flutter SDK version

3.5.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by passerby-yyds** [comment]
me too

**Comment by BlackLeg15** [comment]
Up. I'm getting that problem, too

**Comment by jennantilla** [comment]
Hello there! Apologies that this issue was missed. Please upgrade to our latest SDK version by following our [migration guide](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/MIGRATION_GUIDE.md). We have new methods for listening for notification clicks/opens. If you have any trouble after upgrading please open a new issue and we will be happy to help. Thanks!
