### ISSUE TITLE
[Bug]: Getting error when tryping to run on iOS17 - XCode 15

### ISSUE THREAD

**Issue by dchandrani** [OneSignal/OneSignal-Flutter-SDK#746]
### What happened?

I updated my Xcode and migrated onesignal_flutter to 5.0.1. I have also updated pod file as instructed (pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'). 

Still, I'm getting this error: 
Error (Xcode): Framework 'OneSignal' not found

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

### Steps to reproduce?

```Markdown
1. Use XCode 15
2. Updated onesignal_flutter: ^5.0.1
3. Run project on simulator
```

### What did you expect to happen?

You might encounter following error:

Failed to build iOS app
Error (Xcode): Framework 'OneSignal' not found

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 15.

### OneSignal Flutter SDK version

5.0.1

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
Xcode build done.                                           17.6s
Failed to build iOS app
Error (Xcode): Framework 'OneSignal' not found

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPhone 15.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
Hello I apologize we are working on updating our migration guide [here](https://github.com/OneSignal/OneSignal-Flutter-SDK/pull/744/files). You likely need to update your import in your Notification Service Extension to be `OneSignalFramework/OneSignalFramework.h`

**Comment by michael-joseph-payne** [comment]
This has been an enormous time suck trying to migrate - and now I'm finding out the docs aren't finished yet.

**Comment by emawby** [comment]
@tgloc96 Interesting I am not able to reproduce that. The only similar issue I have found is [this one](https://github.com/aws/amazon-chime-sdk-ios/issues/163) in another SDK

**Comment by ThakarRajesh** [comment]
Hello @dchandrani 
I had the same problem. That is how I resolved it.
Change OneSignal to OneSignalFramework in the NotificationService.swift file to make it work in my app.
![Screenshot 2023-09-25 at 2 40 30 PM](https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/14832892/5a0b48bf-529d-4023-8661-fe745090eff1)

**Comment by dchandrani** [comment]
@ThakarRajesh It's not working in my case.

<img width="799" alt="Screenshot 2023-09-25 at 3 28 13 PM" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/10478346/09368fdf-a05a-40ae-815b-af09f1d29e7f">

**Comment by dchandrani** [comment]
@ThakarRajesh Getting error Framework 'OneSignal' not found.

<img width="1142" alt="Screenshot 2023-09-25 at 3 33 31 PM" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/10478346/d17f16e7-20e0-4a57-b84d-4d7d9109f2c5">

**Comment by husainazkas** [comment]
same here after upgrade xcode version to 15

**Comment by emawby** [comment]
That issue is usually with cocoapods having bad derived/cached data, however I would need to see your podfile to confirm.

However you also have the option of not using Cocoapods for the notification service extension target. 
You could try the following:
Remove OneSignal from your NotificationServiceExtension section of your podfile completely. Then in Xcode navigate to the Notification Service Extension project settings and add the following XCFrameworks as dependencies:
OneSignalCore.xcframework
OneSignalOutcomes.xcframework
OneSignalExtension.xcframework

<img width="626" alt="image" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/13123372/50ff38e0-59f5-4450-acef-76fb7e650472">

It should now look like this
<img width="658" alt="image" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/13123372/058c4399-c5e1-4911-ada0-bae3ceca92f7">

**Comment by dchandrani** [comment]
@emawby Did add the way you have mentioned. But still not able to build the project.

<img width="1134" alt="Screenshot 2023-09-27 at 10 16 19 PM" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/10478346/64083087-c519-41be-aa2b-5ac72a1f4068">

**Comment by andj207** [comment]
Add like _emawby_ mentioned and `import OneSignalFramework` works for me.

**Comment by emawby** [comment]
> @emawby Did add the way you have mentioned. But still not able to build the project.
> 
> <img alt="Screenshot 2023-09-27 at 10 16 19 PM" width="1134" src="https://user-images.githubusercontent.com/10478346/271055283-64083087-c519-41be-aa2b-5ac72a1f4068.png">

Sorry like andj207 mentioned you also must `import OneSignalFramework`

**Comment by temcewen** [comment]
@emawby import OneSignalFramework in what file?

**Comment by secretmoo35** [comment]
> The same problem, and I looked at this, it works.
> 
> https://stackoverflow.com/questions/77187534/cycle-inside-project-building-could-produce-unreliable-results-cycle-details


1. You can use OneSignal as is without the need to import anything additional.
2. Open "TARGETS > Runner > Build Phases" and move "Embed Foundation Extensions" Above "Thin Binary"

<img width="1519" alt="Screenshot 2566-10-03 at 09 08 39" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/14917784/b82340b8-4947-40c4-b911-28d184ad16ab">
<img width="1535" alt="Screenshot 2566-10-03 at 09 08 28" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/14917784/453fe742-e0ab-4d21-b357-4440b662af8a">
<img width="1526" alt="Screenshot 2566-10-03 at 09 09 43" src="https://github.com/OneSignal/OneSignal-Flutter-SDK/assets/14917784/24036cf7-a313-4243-b157-99b840fa4f17">

**Comment by temcewen** [comment]
@secretmoo35 I appreciate the response, but I had already tried that and it didn't work.

@emawby I was able to figure out what you meant by `import OneSignalFramework`, but I was using Objective-C instead of Swift at the time so I didn't figure it out till I tried to switch. It's working for me now. I do wonder what the import would have been for the Objective-C version.

**Comment by temcewen** [comment]
@shkvoretz Nobody can help you without specifics. Are you getting the exact same error: "'OneSignal' not found"?

If so, follow the instructions that @emawby said to do, use Swift instead of Objective-C for your Notification Service Extension, and then copy this code into the Notification.swift under the OneSignalNotificationServiceExtension folder:

> `import UserNotifications

import OneSignalFramework

class NotificationService: UNNotificationServiceExtension {
    
    var contentHandler: ((UNNotificationContent) -> Void)?
    var receivedRequest: UNNotificationRequest!
    var bestAttemptContent: UNMutableNotificationContent?
    
    override func didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
        self.receivedRequest = request
        self.contentHandler = contentHandler
        self.bestAttemptContent = (request.content.mutableCopy() as? UNMutableNotificationContent)
        
        if let bestAttemptContent = bestAttemptContent {
            //If your SDK version is < 3.5.0 uncomment and use this code:
            /*
            OneSignal.didReceiveNotificationExtensionRequest(self.receivedRequest, with: self.bestAttemptContent)
            contentHandler(bestAttemptContent)
            */
            
            /* DEBUGGING: Uncomment the 2 lines below to check this extension is excuting
                          Note, this extension only runs when mutable-content is set
                          Setting an attachment or action buttons automatically adds this */
            //OneSignal.setLogLevel(.LL_VERBOSE, visualLevel: .LL_NONE)
            //bestAttemptContent.body = "[Modified] " + bestAttemptContent.body
            
            OneSignal.didReceiveNotificationExtensionRequest(self.receivedRequest, with: bestAttemptContent, withContentHandler: self.contentHandler)
        }
    }
    
    override func serviceExtensionTimeWillExpire() {
        // Called just before the extension will be terminated by the system.
        // Use this as an opportunity to deliver your "best attempt" at modified content, otherwise the original push payload will be used.
        if let contentHandler = contentHandler, let bestAttemptContent =  bestAttemptContent {
            OneSignal.serviceExtensionTimeWillExpireRequest(self.receivedRequest, with: self.bestAttemptContent)
            contentHandler(bestAttemptContent)
        }
    }
    
}
`

**Comment by temcewen** [comment]
> OneSignal integration is very frustrating, the amount of effort that we invested in constantly getting this thing to work has been massive. If this isn't resolved in timely manner we'll be switching.

I know it seems difficult, but I think all notification service providers have a tough setup, and from what I've heard, OneSignal has the best service with one of the easiest setups. The issue is that they are doing a huge update from 3.x to 5.x. It's frustrating for sure, I spend 8 hours of a 12 hour day on fixing our implementation yesterday. However, the alternatives are probably worse, you're welcome to try them out though.

**Comment by temcewen** [comment]
I'm starting to agree with @shkvoretz

This OneSignal update has been one of the most frustrating things I have ever had to deal with in my whole career. I have probably spent about 30 hours this week trying to fix it. It just broke again tonight and I am pretty much on the verge of giving up. 

PLEASE ROLL IT BACK. Put an update out once it's actually stable. This is awful. 

@Jeasmine @Nightsd01 @mikechoch @emawby

**Comment by emawby** [comment]
@shkvoretz Unfortunately these issues are with Cocoapods/NotificationServiceExtensions and are hard to debug if we cannot reproduce them. If none of the solutions in these threads have resolved your issue could you share a sample project that is experiencing the problem?

**Comment by Vedsaga** [comment]
>In case it's Friday afternoon or anytime after 1am:
>Opening xcodeproj instead of xcworkspace will cause an error like this...

https://stackoverflow.com/questions/29500227/getting-error-no-such-module-using-xcode-but-the-framework-is-there

Solved it... Phew after 3 days
