### ISSUE TITLE
[Bug]: Example on GitHub uses a version prior to 5.0.0 and doesn't match the one displayed on pub.dev

### ISSUE THREAD

**Issue by Jannik-dev** [OneSignal/OneSignal-Flutter-SDK#749]
### What happened?

The example on pub.dev (https://pub.dev/packages/onesignal_flutter/example) doesn't match the one on GitHub (https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/example/lib/main.dart).

### Steps to reproduce?

```Markdown
Look at https://pub.dev/packages/onesignal_flutter/example and look at https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/main/example/lib/main.dart
```

### What did you expect to happen?

Both should be the same → GitHub example should be adjusted

### OneSignal Flutter SDK version

None

### Which platform(s) are affected?

- [ ] iOS
- [ ] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @Jannik-dev, thank you for reporting this. 

We recently released a new major version `5.x.x` that lives on this branch [`user_model/main`](https://github.com/OneSignal/OneSignal-Flutter-SDK/blob/user_model/main/example/lib/main.dart).

Our `main` branch on GitHub is currently on the previous version since we have not merged the new release to main yet. We are currently focused on responding to feedback and bug reports, but reconciling our major release with the `main` branch is one of the steps we will do. When that happens, the example on pub.dev and the one on the `main` branch in GitHub will match!
