### ISSUE TITLE
[question]: How to fix this error message when building IOS

### ISSUE THREAD

**Issue by claptonorioste** [OneSignal/OneSignal-Flutter-SDK#751]
### How can we help?

The following build commands failed:
	CodeSign /Users/kahero/Library/Developer/Xcode/DerivedData/Runner-bfzttzdxabswezcscrqzncnygauc/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/OneSignalNotificationServiceExtension.appex (in target 'OneSignalNotificationServiceExtension' from project 'Runner')
(1 failure)
ERROR [2023-09-26 11:49:02.83]: Exit status: 65

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by husainazkas** [comment]
Same here, after upgrade xcode version to 15

**Comment by emawby** [comment]
@claptonorioste You could try the steps from [this comment](https://github.com/OneSignal/OneSignal-Flutter-SDK/issues/746#issuecomment-1737733321) that link OneSignal without using Cocoapods for the Notification Service Extension target

**Comment by rodrigorafaeldamaceno** [comment]
Same problem here

**Comment by rodrigorafaeldamaceno** [comment]
Cycle inside Runner; building could produce unreliable results. This usually can be resolved by moving the shell script phase 'Thin Binary' so that it runs before the build phase that depends on its outputs.
Cycle details:
→ Target 'Runner' has a command with output '.../ios/build/Debug-develop-iphoneos/Runner.app.dSYM'
○ Target 'Runner' has process command with output '.../ios/build/Debug-develop-iphoneos/Runner.app/Info.plist'
○ Target 'Runner' has copy command from '.../ios/build/Debug-develop-iphoneos/OneSignalNotificationServiceExtension.appex' to '.../ios/build/Debug-develop-iphoneos/Runner.app/PlugIns/OneSignalNotificationServiceExtension.appex'
○ That command depends on command in Target 'Runner': script phase “[CP] Embed Pods Frameworks”
○ That command depends on command in Target 'Runner': script phase “Thin Binary”

**Comment by zvikarp** [comment]
I have faced the same issue and fixed it by going to the main Runner "Build Phases" > "Embed Foundation Extensions" and toggling on the checkbox "Copy only when installing".

Got the solution from here: https://stackoverflow.com/a/77192573/4465386

I recommend @OneSignal add this info to a migration guide to upgrade to xcode 15.

**Comment by emawby** [comment]
@rodrigorafaeldamaceno That likely means there is a difference between your 'debug' and 'release' build configurations. Does building to a device with the release configuration work?

**Comment by rodrigorafaeldamaceno** [comment]
@emawby Yes, I can run the app in release version and install it on the device, but when generating the archive for testflight, the error occurs, Is yours working correctly?

**Comment by claptonorioste** [comment]
i have fixed my issue by adding unlock keychain in fastlane also check keyaccess if there are expired certificate mine was Apple Worldwide Developer Relations Certification Authority Intermediate Certificate was expired

`unlock_keychain(
      path: "/Users/xxxxxxx/xxxxxxxx/login.keychain-db",
      password: "************"
    )`

**Comment by saulopef** [comment]
@claptonorioste Hi, Are you using match on fastlane? if yes, can you provide a sample of your exportOptions? I'm getting trouble to use match with onesignal extension
