### ISSUE TITLE
[Bug]: OneSignal SDK 5.1.0 - Connection Error: "nw_resolver_start_query_timer_block_invoke [C1.1.1] Query Timeout

### ISSUE THREAD

**Issue by burhanaksendir** [OneSignal/OneSignal-Flutter-SDK#850]
### What happened?

I am using OneSignal SDK version 5.1.0, and consistently encountering the error "nw_resolver_start_query_timer_block_invoke [C1.1.1] Query fired: did not receive all answers in time for api.onesignal.com:443" in the application logs. This error indicates a connection issue with the OneSignal API.

### Steps to reproduce?

```Markdown
Launch the application.
Check the logs for the error message "nw_resolver_start_query_timer_block_invoke [C1.1.1] Query fired: did not receive all answers in time for api.onesignal.com:443."
```

### What did you expect to happen?

I expected the OneSignal SDK to function stably without encountering the "nw_resolver_start_query_timer_block_invoke [C1.1.1] Query fired: did not receive all answers in time for api.onesignal.com:443" error.

### OneSignal Flutter SDK version

5.1.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
nw_resolver_start_query_timer_block_invoke [C1.1.1] Query fired: did not receive all answers in time for api.onesignal.com:443
nw_resolver_start_query_timer_block_invoke [C2.1.1] Query fired: did not receive all answers in time for api.onesignal.com:443
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello there--apologies that this issue was missed.

This could be caused by a number of things, including Network Instability, DNS Issues, or a Firewall. 

After you check these settings, please update to our [latest SDK](https://github.com/OneSignal/OneSignal-Flutter-SDK/releases/tag/5.2.8). If you are still having problems, please create a new issue with a debug log and we'll be happy to help investigate further!
