### ISSUE TITLE
[Bug]: OneSignal Initialization Fails with Null AppId - "FATAL: OneSignal AppId: (null)"

### ISSUE THREAD

**Issue by burhanaksendir** [OneSignal/OneSignal-Flutter-SDK#852]
### What happened?

OneSignal initialization fails with the following error message: "FATAL: OneSignal AppId: (null) - AppId is null or format is invalid, stopping initialization."

### Steps to reproduce?

```Markdown
1. Initialize OneSignal in the Flutter application with a valid AppId.
2. Ensure that the AppId is correct and in the proper format.
3. Run the application for the first time.
4. Observe the error in the log output.
```

### What did you expect to happen?

I expected OneSignal to initialize successfully without any errors when providing a valid AppId.

### OneSignal Flutter SDK version

5.1.0

### Which platform(s) are affected?

- [X] iOS
- [ ] Android

### Relevant log output

```Shell
FATAL: OneSignal AppId: (null) - AppId is null or format is invalid, stopping initialization.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nan-li** [comment]
Hi @burhanaksendir, thanks for reporting. This is a misleading log on a new app install. Initialization did not fail.

This is logged by the native iOS SDK that the Flutter SDK calls into and the app ID has not been set YET by the developer. The Flutter SDK needs initialize the native iOS SDK in order to pass along iOS launch options very early in the app startup process.

If you turn on verbose-level logging, you should see `VERBOSE: setAppId called with appId: <YOUR_APP_ID>` being logged shortly after the Fatal log you reported. Sorry for any confusion this log caused.
