### ISSUE TITLE
[Bug]:  Our OneSignal Tags are being deleted for no reason.

### ISSUE THREAD

**Issue by topkarat6** [OneSignal/OneSignal-Flutter-SDK#950]
### What happened?

After users log in to One Signal, we fill in their tags, and then when I turn off the phone screen or close the application, our tags are deleted.

### Steps to reproduce?

```Markdown
OneSignal.Debug.setLogLevel(OSLogLevel.verbose);
  OneSignal.initialize("776513db-e536-441a-8d2b-b446cd6be842");
  OneSignal.Notifications.requestPermission(true);
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);



  await read.loginUserOneSignal();
```

### What did you expect to happen?

cdfsrgfd

### OneSignal Flutter SDK version

onesignal_flutter: ^5.2.3

### Which platform(s) are affected?

- [x] iOS
- [X] Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jennantilla** [comment]
Hello @topkarat6 apologies for the delay in getting back to you. Since it's been several weeks since you reported this, I am going to close this issue but wanted to follow up and see if you are still encountering problems. If so, can you please provide the [debug logs](https://documentation.onesignal.com/docs/capturing-a-debug-log) from your device so we can see what is going on? Thanks!
